### ISSUE TITLE
在DllMain里面调用send会卡死 

### ISSUE THREAD

**Issue by YDHCUI** [neonmoe/minreq#85] opened 2022-11-11 02:25 UTC
```rust 
use tokio::runtime::Runtime;

#[no_mangle]
#[allow(non_snake_case)]
pub unsafe extern "system" fn DllMain(_: i32, reason: i32, _: i32) -> i32 {
    match reason{
        1 => func(),
        0|_ => {}
    }
    1
}

fn func(){
    if let Ok(rt) = Runtime::new(){
        rt.block_on(async {
            loop{
               event2().await; 
            }
            
        })
    };
}

async fn event1(){
    println!("111111111111111");
    let response = minreq::get("https://github.com/neonmoe/minreq/issues")
                .send()
                .unwrap();
    println!("{}", response.status_code);
}

async fn event2(){
    println!("111111111111111");
    let response = minreq::get("https://github.com/neonmoe/minreq/issues")
                .with_timeout(60).send()
                .unwrap();
    println!("{}", response.status_code);
}

```

如上代码 在dllmain里面调用event1是正常的 但如果像event2那样在send前加上timeout 的话程序会卡死。
![image](https://user-images.githubusercontent.com/46884495/201251391-657a8b71-f516-45a9-b36f-cd7a91ed037a.png)

**Comment by neonmoe** [comment] 2022-11-11 19:07
I am not very familiar with Windows's DllMain, so I can't say if that's the issue here. I can say that the following seems to work just fine for me, which seems to cover most of the code you gave:

```rust
use tokio::runtime::Runtime;

fn main() {
    if let Ok(rt) = Runtime::new() {
        rt.block_on(async {
            loop {
                event2().await;
            }
        });
    }
}

async fn event2() {
    println!("111111111111111");
    let response = minreq::get("https://github.com/neonmoe/minreq/issues")
        .with_timeout(60)
        .send()
        .unwrap();
    println!("{}", response.status_code);
}
```
This prints the following for me:
```
111111111111111
200
111111111111111
200
111111111111111
200
...and so on
```

I doubt the issue is with this crate, so I'll close this. If you do figure it out, feel free to comment about the solution, it might help someone else.

**Closed by neonmoe** 2022-11-11 19:07 UTC
