### ISSUE TITLE
"invalid port value" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [neonmoe/minreq#51] opened 2021-02-16 23:23 UTC
On some websites, e.g. http://serveblog.net, minreq fails with the following error:

> invalid port value

Firefox and curl work fine.

126 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/minreq-smoke-test/src/main.rs). Test tool output from all affected websites: [minreq-invalid-port.tar.gz](https://github.com/neonmoe/minreq/files/5992214/minreq-invalid-port.tar.gz)

**Comment by neonmoe** [comment] 2021-02-16 23:37
I suspect this is caused by the given websites specifying their port in some funky way which would involve doing DNS or other figuring-out-requests, in which case I'm inclined to close this as out-of-scope. Minreq isn't a general-purpose browser, after all.

Anyway, I'll look into this (and the others) when I find the time.

**Comment by neonmoe** [comment] 2021-05-09 20:34
Seems that these are caused by server misconfiguration, and since minreq is supposed to be minimal, breakage is expected. Some examples:

- allmyfaves.ca redirects to https://ca:80
- www.link11.com redirects to https://www.link11.comhttps://www.link11.com/en/
- sokhahotels.com redirects to http://sokhahotels.com:80.kh
- gset.co.jp redirects to https://gset.co.jp:/

And so on. I'll have a look at the error being reported though, there might be something to improve there.

**Closed by neonmoe** 2021-05-09 20:34 UTC
