### ISSUE TITLE
Failing HTTPS requests to GitHub API

### ISSUE THREAD

**Issue by tech-ticks** [neonmoe/minreq#66] opened 2022-01-06 19:14 UTC
Requests to the GitHub API consistently fail with `IoError(Custom { kind: ConnectionAborted, error: "CloseNotify alert received" })` under rustls. `reqwest` returns a response with code 403 instead.

**How to reproduce:**
- Enable the `https` feature 
- `minreq::get("https://api.github.com/zen").send().unwrap();` (note that the request works if the `User-Agent` header is set)

**Comment by neonmoe** [comment] 2022-01-06 21:12
Thanks for the report, what an odd issue. I'll look into it.

**Comment by neonmoe** [comment] 2022-01-06 22:33
Seems to be caused by rustls 0.19, updating to 0.20 fixed it. I'll publish a patch soon.

**Comment by neonmoe** [comment] 2022-01-06 23:20
Fixed in 841cf11b3579d4fe546d4a669182a685280219ae, released with [2.5.1](https://github.com/neonmoe/minreq/releases/tag/2.5.1).

**Closed by neonmoe** 2022-01-06 23:20 UTC
